language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.8.0"
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls
script:
  - coverage run --source=incapsula -m nose2.__main__ -v
after_success:
  - coveralls